# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: balee <balee@student.42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/11/27 21:21:44 by balee             #+#    #+#              #
#    Updated: 2022/12/08 02:39:58 by balee            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME		= ex03
SRCS		= main.cpp ClapTrap.cpp ScavTrap.cpp FragTrap.cpp DiamondTrap.cpp

CXXFLAGS	= -Wall -Werror -Wextra -std=c++98 -Wshadow -Wno-shadow

include		../template.mk
