# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: balee <balee@student.42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/11/27 21:17:06 by balee             #+#    #+#              #
#    Updated: 2022/11/27 21:17:06 by balee            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME		= unnecessaryViolence
SRCS		= main.cpp Weapon.cpp HumanA.cpp HumanB.cpp

include		../template.mk
